namespace API_Gateway.Models.Dto
{
    public class OrderItemDetails
    {
        public int? RowNumber { get; set; }
        public int? PageCount { get; set; }
        public int? RecordCount { get; set; }
        public int? OrderId { get; set; }
        public int? OrderItemId { get; set; }
        public string? Guid { get; set; }
        public string? OrderNo { get; set; }
        public string? SubOrderNo { get; set; }
        public string? OrderReferenceNo { get; set; }
        public string? SellerID { get; set; }
        public int? BrandID { get; set; }
        public int? ProductID { get; set; }
        public string? ProductGUID { get; set; }
        public int? SellerProductID { get; set; }
        public int? CategoryId { get; set; }
        public string? ProductName { get; set; }
        public string? ProductSKUCode { get; set; }
        public decimal? MRP { get; set; }
        public decimal? SellingPrice { get; set; }
        public decimal? Discount { get; set; }
        public int? Qty { get; set; }
        public int? SizeID { get; set; }
        public string? SizeValue { get; set; }
        public int? PriceTypeID { get; set; }
        public string? PriceType { get; set; }
        public decimal? ItemTotalAmount { get; set; }
        public int? WherehouseId { get; set; }
        public int? OrderTaxRateId { get; set; }
        public string? HSNCode { get; set; }
        public string? OrderTaxRate { get; set; }
        public string? ColorName { get; set; }
        public string? ProductImage { get; set; }
        public string? WeightSlab { get; set; }
        public string? UserId { get; set; }
        public string? UserName { get; set; }
        public string? UserPhoneNo { get; set; }
        public string? UserEmail { get; set; }
        public string? UserAddressLine1 { get; set; }
        public string? UserAddressLine2 { get; set; }
        public string? UserLandmark { get; set; }
        public string? UserCity { get; set; }
        public string? UserState { get; set; }
        public string? UserCountry { get; set; }
        public string? UserPincode { get; set; }
        public string? UserGSTNo { get; set; }
        public bool? IsCouponApplied { get; set; }
        public string? Coupon { get; set; }
        public decimal? CoupontDiscount { get; set; }
        public bool? ItemIsCouponApplied { get; set; }
        public string? ItemCoupon { get; set; }
        public decimal? ItemCouponDiscount { get; set; }
        public string? ItemCoupontDetails { get; set; }
        public bool? IsSale { get; set; }
        public string? SaleType { get; set; }
        public string? OrderStatus { get; set; }
        public string? ItemStatus { get; set; }
        public bool? IsSellerWithGSTAtOrderTime { get; set; }
        public int? OrderTaxInfoId { get; set; }
        public string? CommissionIn { get; set; }
        public decimal? CommissionRate { get; set; }
        public decimal? CommissionAmount { get; set; }
        public decimal? TaxOnCommission { get; set; }
        public string? OtaxShipmentBy { get; set; }
        public string? OtaxShipmentPaidBy { get; set; }
        public string? OtaxShippingZone { get; set; }
        public decimal? OtaxShippingCharge { get; set; }
        public decimal? OtaxOnShipping { get; set; }
        public decimal? NetEarn { get; set; }
        public int? PackageId { get; set; }
        public string? PackageNo { get; set; }
        public int? NoOfPackage { get; set; }
        public int? TotalItems { get; set; }
        public decimal? PackageAmount { get; set; }
        public decimal? PackageCodCharges { get; set; }
        public string? PaymentMode { get; set; }
        public string? ShippingZone { get; set; }
        public string? ShippingChargePaidBy { get; set; }
        public decimal? ShippingCharge { get; set; }
        public decimal? SubTotal { get; set; }
        public decimal? TotalShippingCharge { get; set; }
        public decimal? TotalExtraCharges { get; set; }
        public decimal? TotalAmount { get; set; }
        public decimal? CODCharge { get; set; }
        public decimal? PaidAmount { get; set; }
        public bool? IsRetailer { get; set; }
        public bool? IsVertualRetailer { get; set; }
        public bool? IsReplace { get; set; }
        public int? ParentID { get; set; }
        public bool? ItemReplace { get; set; }
        public int? ItemParentId { get; set; }
        public string? ReturnPolicyName { get; set; }
        public string? ReturnPolicyTitle { get; set; }
        public string? ReturnPolicyCovers { get; set; }
        public string? ReturnPolicyDescription { get; set; }
        public int? ReturnValidDays { get; set; }
        public string? OrderItemIDs { get; set; }
        public DateTime? ReturnValidTillDate { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public string? OrderWiseExtraCharges { get; set; }
        public string? OrderWiseExtendedWarranty { get; set; }
        public string? OrderWiseProductSeriesNo { get; set; }
        public string? OrderWiseProductVariantMapping { get; set; }
        public string? OrderTrackDetails { get; set; }
        public string? ExtraDetails { get; set; }
        public string? PaymentInfo { get; set; }
        public string? OrderBy { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}
